name: login_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.2.0
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Menambahkan assets untuk logo atau gambar lainnya
  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/logo.png

  # Aset gambar/logo yang digunakan di aplikasi
